const patient_dummy_data = [
  {
    id: 1,
    patient_name: 'Art Shimwell',
    admission_date: '24/06/2022',
    discharge_date: '19/05/2023',
    gender: 'Male',
    room: 'Desert Thistle',
    birth: '20/01/2018',
    hr: 103,
    rr: 30,
    spo2: 41,
    temp: 35.6,
    sistolik: 147,
    diastolik: 81,
    id_card: 5050500541,
    address: '2356 Lindbergh Center',
    contact: 2781792396,
    education: 'Texas Tech University Health Science Center',
    occupation: 'Business Development',
    height: 123,
    weight: 158,
    blood: 'Violet',
    covid: false,
    test_type: false,
    result: true,
    referred: 'AMOREPACIFIC',
    note: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    ward: 'CA-BC',
    photo: 'IntegerANibh.mp3',
  },
  {
    id: 2,
    patient_name: 'Syd Stripp',
    admission_date: '13/06/2022',
    discharge_date: '05/05/2023',
    gender: 'Male',
    room: 'Hybrid Violet',
    birth: '18/12/2016',
    hr: 155,
    rr: 15,
    spo2: 84,
    temp: 28.8,
    sistolik: 176,
    diastolik: 33,
    id_card: 2572638875,
    address: '993 Redwing Drive',
    contact: 2854474423,
    education: 'Morris Brown College',
    occupation: 'Product Management',
    height: 285,
    weight: 183,
    blood: 'Puce',
    covid: true,
    test_type: false,
    result: false,
    referred: 'Procter & Gamble Manufacturing Company',
    note: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    ward: 'US-FL',
    photo: 'VestibulumAnteIpsum.avi',
  },
  {
    id: 3,
    patient_name: 'Darsie Espinet',
    admission_date: '17/05/2022',
    discharge_date: '28/07/2023',
    gender: 'Female',
    room: 'Purpleflowering Raspberry',
    birth: '24/11/2017',
    hr: 65,
    rr: 28,
    spo2: 44,
    temp: 27.7,
    sistolik: 164,
    diastolik: 46,
    id_card: 3274208228,
    address: '4592 Roth Terrace',
    contact: 9804136729,
    education: 'Pennsylvania State University - Altoona',
    occupation: 'Human Resources',
    height: 56,
    weight: 115,
    blood: 'Maroon',
    covid: false,
    test_type: true,
    result: true,
    referred: 'Walgreen Company',
    note: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    ward: 'MY-15',
    photo: 'ElementumLigulaVehicula.ppt',
  },
  {
    id: 4,
    patient_name: 'Enrica Fitter',
    admission_date: '29/09/2022',
    discharge_date: '04/07/2023',
    gender: 'Female',
    room: "Leonard's Beardtongue",
    birth: '27/05/2020',
    hr: 60,
    rr: 30,
    spo2: 86,
    temp: 30.9,
    sistolik: 196,
    diastolik: 32,
    id_card: 9635025222,
    address: '4402 Kinsman Place',
    contact: 1359496367,
    education: 'Tunghai University',
    occupation: 'Engineering',
    height: 258,
    weight: 64,
    blood: 'Violet',
    covid: false,
    test_type: true,
    result: true,
    referred: 'CVS PHARMACY',
    note: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    ward: 'ID-BA',
    photo: 'Aenean.avi',
  },
  {
    id: 5,
    patient_name: 'Maybelle Demangel',
    admission_date: '06/08/2022',
    discharge_date: '27/05/2023',
    gender: 'Female',
    room: 'Golden Polypody',
    birth: '16/12/2018',
    hr: 95,
    rr: 24,
    spo2: 82,
    temp: 30.0,
    sistolik: 134,
    diastolik: 98,
    id_card: 2912099779,
    address: '02382 Burning Wood Way',
    contact: 5094615062,
    education: 'Shenyang Polytechnic University',
    occupation: 'Legal',
    height: 160,
    weight: 124,
    blood: 'Turquoise',
    covid: true,
    test_type: false,
    result: true,
    referred: 'HEB',
    note: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    ward: 'PR-U-A',
    photo: 'PurusSit.txt',
  },
  {
    id: 6,
    patient_name: 'Davin McWhan',
    admission_date: '26/10/2022',
    discharge_date: '03/05/2023',
    gender: 'Male',
    room: 'Santa Catalina Prairie Clover',
    birth: '25/04/2019',
    hr: 92,
    rr: 20,
    spo2: 68,
    temp: 28.4,
    sistolik: 154,
    diastolik: 45,
    id_card: 5527555857,
    address: '455 Pierstorff Circle',
    contact: 8887287566,
    education: 'Tezpur University',
    occupation: 'Training',
    height: 127,
    weight: 126,
    blood: 'Puce',
    covid: false,
    test_type: false,
    result: false,
    referred: 'Supervalu Inc',
    note: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    ward: 'PG-WPD',
    photo: 'MusVivamus.mpeg',
  },
  {
    id: 7,
    patient_name: 'Felipe Toderbrugge',
    admission_date: '29/10/2022',
    discharge_date: '21/07/2023',
    gender: 'Male',
    room: "Heller's Cudweed",
    birth: '30/03/2021',
    hr: 97,
    rr: 16,
    spo2: 93,
    temp: 38.6,
    sistolik: 103,
    diastolik: 44,
    id_card: 2010256394,
    address: '49 Carpenter Drive',
    contact: 9253775410,
    education: 'Universität Hohenheim',
    occupation: 'Human Resources',
    height: 86,
    weight: 131,
    blood: 'Teal',
    covid: false,
    test_type: false,
    result: false,
    referred: 'Mylan Pharmaceuticals Inc.',
    note: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    ward: 'JP-43',
    photo: 'VivamusTortorDuis.mp3',
  },
  {
    id: 8,
    patient_name: 'Felisha Keneleyside',
    admission_date: '08/07/2022',
    discharge_date: '01/06/2023',
    gender: 'Female',
    room: 'Cup Lichen',
    birth: '26/01/2018',
    hr: 156,
    rr: 28,
    spo2: 68,
    temp: 36.4,
    sistolik: 140,
    diastolik: 30,
    id_card: 8459780614,
    address: '3813 Delaware Road',
    contact: 7079977899,
    education: 'Universitas Mercu Buana',
    occupation: 'Legal',
    height: 118,
    weight: 22,
    blood: 'Purple',
    covid: false,
    test_type: false,
    result: false,
    referred: 'Uriel Pharmacy Inc.',
    note: 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    ward: 'BR-CE',
    photo: 'MagnaAcConsequat.png',
  },
  {
    id: 9,
    patient_name: 'Rosalia Abate',
    admission_date: '10/09/2022',
    discharge_date: '23/05/2023',
    gender: 'Female',
    room: 'Wyoming Besseya',
    birth: '20/10/2021',
    hr: 121,
    rr: 14,
    spo2: 73,
    temp: 37.7,
    sistolik: 197,
    diastolik: 49,
    id_card: 5393530316,
    address: '60137 Russell Hill',
    contact: 3001714388,
    education: 'Akhbar El Yom Academy',
    occupation: 'Engineering',
    height: 188,
    weight: 199,
    blood: 'Mauv',
    covid: false,
    test_type: true,
    result: true,
    referred: 'Aurolife Pharma LLC',
    note: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    ward: 'BD-5',
    photo: 'LuctusUltriciesEu.mp3',
  },
  {
    id: 10,
    patient_name: 'Krysta Lusgdin',
    admission_date: '26/06/2022',
    discharge_date: '27/06/2023',
    gender: 'Female',
    room: "Parks' Croton",
    birth: '24/10/2019',
    hr: 174,
    rr: 14,
    spo2: 81,
    temp: 29.8,
    sistolik: 189,
    diastolik: 38,
    id_card: 9457855385,
    address: '76874 Thierer Junction',
    contact: 2982976835,
    education: 'Middle Tennessee State University',
    occupation: 'Accounting',
    height: 112,
    weight: 32,
    blood: 'Khaki',
    covid: false,
    test_type: true,
    result: false,
    referred: 'Citron Pharma LLC',
    note: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    ward: 'BR-RJ',
    photo: 'InHacHabitasse.mov',
  },
  {
    id: 11,
    patient_name: 'Even',
    admission_date: '23/05/2022',
    discharge_date: '',
    gender: 'Male',
    room: 'Annual Monsterwort',
    birth: '06/01/2018',
    hr: 81,
    rr: 16,
    spo2: 74,
    temp: 32.8,
    sistolik: 117,
    diastolik: 75,
    id_card: 8369701505,
    address: '56737 Jackson Pass',
    contact: 3744728348,
    education: 'Spiru Haret University',
    occupation: 'Human Resources',
    height: 158,
    weight: 22,
    blood: 'Aquamarine',
    covid: false,
    test_type: true,
    result: true,
    referred: 'Teva Pharmaceuticals USA Inc',
    note: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    ward: 'US-NJ',
    photo: 'Quam.txt',
  },
  {
    id: 12,
    patient_name: 'Hedy Asling',
    admission_date: '22/03/2022',
    discharge_date: '11/07/2023',
    gender: 'Female',
    room: "Havard's Ipomopsis",
    birth: '17/06/2017',
    hr: 77,
    rr: 28,
    spo2: 88,
    temp: 30.4,
    sistolik: 191,
    diastolik: 62,
    id_card: 6818927140,
    address: '1 Anniversary Junction',
    contact: 6317136971,
    education: 'Kosin University',
    occupation: 'Services',
    height: 109,
    weight: 152,
    blood: 'Teal',
    covid: true,
    test_type: true,
    result: false,
    referred: 'Cardinal Health',
    note: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    ward: 'MY-12',
    photo: 'Mauris.tiff',
  },
  {
    id: 13,
    patient_name: 'Muhamad Ivan Fadilah',
    admission_date: '25/05/2022',
    discharge_date: '',
    gender: 'Male',
    room: 'Ridgetop Bloodgrass',
    birth: '12/07/2021',
    hr: 117,
    rr: 16,
    spo2: 93,
    temp: 35.5,
    sistolik: 165,
    diastolik: 97,
    id_card: 1995656535,
    address: '808 Spaight Parkway',
    contact: 3566801264,
    education: 'Shahjalal University of Science and Technology',
    occupation: 'Support',
    height: 225,
    weight: 84,
    blood: 'Turquoise',
    covid: false,
    test_type: false,
    result: false,
    referred: 'Natural Creations, Inc.',
    note: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    ward: 'LY-BU',
    photo: 'PhasellusIn.doc',
  },
  {
    id: 14,
    patient_name: 'Evenetus Worshiper Purba',
    admission_date: '30/05/2022',
    discharge_date: '30/06/2023',
    gender: 'Male',
    room: 'Bush Vetch',
    birth: '24/10/2019',
    hr: 60,
    rr: 12,
    spo2: 71,
    temp: 27.7,
    sistolik: 124,
    diastolik: 67,
    id_card: 3495356638,
    address: '702 Jana Court',
    contact: 7523466943,
    education: 'Royal College of Physicians of Ireland',
    occupation: 'Business Development',
    height: 162,
    weight: 128,
    blood: 'Green',
    covid: false,
    test_type: false,
    result: true,
    referred: 'AstraZeneca Pharmaceuticals LP',
    note: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    ward: 'US-NC',
    photo: 'PulvinarSedNisl.ppt',
  },
  {
    id: 15,
    patient_name: 'Ivan',
    admission_date: '19/03/2022',
    discharge_date: '01/06/2023',
    gender: 'Male',
    room: 'Cenizo',
    birth: '06/09/2018',
    hr: 139,
    rr: 20,
    spo2: 35,
    temp: 37.8,
    sistolik: 195,
    diastolik: 38,
    id_card: 9001101342,
    address: '97 High Crossing Avenue',
    contact: 6080352484,
    education: 'Khana-e-Noor Institute of Higher Education',
    occupation: 'Support',
    height: 107,
    weight: 45,
    blood: 'Mauv',
    covid: false,
    test_type: false,
    result: false,
    referred: 'BioActive Nutritional, Inc.',
    note: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    ward: 'AU-QLD',
    photo: 'Eros.xls',
  },
  {
    id: 16,
    patient_name: 'Even',
    admission_date: '03/05/2022',
    discharge_date: '18/06/2023',
    gender: 'Male',
    room: 'Fourleaf Manyseed',
    birth: '24/04/2020',
    hr: 124,
    rr: 25,
    spo2: 91,
    temp: 35.9,
    sistolik: 120,
    diastolik: 78,
    id_card: 6429963533,
    address: '9791 Bartelt Drive',
    contact: 4641142282,
    education: 'Inje University',
    occupation: 'Support',
    height: 80,
    weight: 31,
    blood: 'Turquoise',
    covid: false,
    test_type: true,
    result: false,
    referred: 'SJ Creations, Inc.',
    note: 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    ward: 'US-KS',
    photo: 'AmetEleifendPede.xls',
  },
  {
    id: 17,
    patient_name: 'Alaric',
    admission_date: '30/03/2022',
    discharge_date: '20/06/2023',
    gender: 'Male',
    room: 'Jeffersonia',
    birth: '12/11/2018',
    hr: 149,
    rr: 14,
    spo2: 89,
    temp: 38.5,
    sistolik: 172,
    diastolik: 52,
    id_card: 3088102847,
    address: '96582 Utah Parkway',
    contact: 4997483610,
    education: 'Universidade Cruzeiro do Sul',
    occupation: 'Legal',
    height: 277,
    weight: 77,
    blood: 'Pink',
    covid: true,
    test_type: false,
    result: false,
    referred: 'JAFRA COSMETICS INTERNATIONAL',
    note: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.',
    ward: 'MY-12',
    photo: 'Tincidunt.mp3',
  },
  {
    id: 18,
    patient_name: 'Demetra Prudence',
    admission_date: '09/09/2022',
    discharge_date: '',
    gender: 'Female',
    room: 'Las Animas Nakedwood',
    birth: '05/11/2017',
    hr: 151,
    rr: 21,
    spo2: 73,
    temp: 25.7,
    sistolik: 196,
    diastolik: 93,
    id_card: 1139324315,
    address: '7 Truax Pass',
    contact: 6323902633,
    education: 'Lynn University',
    occupation: 'Human Resources',
    height: 105,
    weight: 183,
    blood: 'Blue',
    covid: true,
    test_type: true,
    result: true,
    referred: 'Sagent Pharmaceuticals, Inc.',
    note: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
    ward: 'JP-28',
    photo: 'DuisBibendum.mp3',
  },
  {
    id: 19,
    patient_name: 'Ameline Cordell',
    admission_date: '10/09/2022',
    discharge_date: '20/07/2023',
    gender: 'Female',
    room: "Coulter's Lyrepod",
    birth: '04/10/2020',
    hr: 111,
    rr: 16,
    spo2: 42,
    temp: 35.8,
    sistolik: 195,
    diastolik: 51,
    id_card: 4463725164,
    address: '4792 Granby Avenue',
    contact: 6753490332,
    education: 'University of the City of Manila',
    occupation: 'Services',
    height: 228,
    weight: 169,
    blood: 'Crimson',
    covid: true,
    test_type: true,
    result: false,
    referred: 'X-GEN Pharmaceuticals, Inc.',
    note: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    ward: 'AO-MOX',
    photo: 'DuiLuctusRutrum.tiff',
  },
  {
    id: 20,
    patient_name: 'Julee Poyzer',
    admission_date: '08/03/2022',
    discharge_date: '15/07/2023',
    gender: 'Female',
    room: "Lady's Tresses",
    birth: '10/10/2018',
    hr: 98,
    rr: 14,
    spo2: 41,
    temp: 26.1,
    sistolik: 165,
    diastolik: 65,
    id_card: 5740672136,
    address: '6 Spenser Avenue',
    contact: 7854014983,
    education: 'Fachhochschulstudiengänge Wels',
    occupation: 'Business Development',
    height: 158,
    weight: 132,
    blood: 'Fuscia',
    covid: false,
    test_type: false,
    result: true,
    referred: 'A P J Laboratories Limited',
    note: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    ward: 'NC-U-A',
    photo: 'PotentiNullam.xls',
  },
  {
    id: 21,
    patient_name: 'Melanie Lamont',
    admission_date: '28/06/2022',
    discharge_date: '26/05/2023',
    gender: 'Female',
    room: 'Birdwing Treefern',
    birth: '07/08/2019',
    hr: 113,
    rr: 30,
    spo2: 50,
    temp: 34.5,
    sistolik: 174,
    diastolik: 66,
    id_card: 7309332830,
    address: '9896 Jenna Park',
    contact: 7065373409,
    education: 'Hamadan University of Medical Sciences',
    occupation: 'Marketing',
    height: 267,
    weight: 93,
    blood: 'Blue',
    covid: true,
    test_type: true,
    result: false,
    referred: 'REMEDYREPACK INC.',
    note: 'In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
    ward: 'BR-SP',
    photo: 'DuisAliquam.ppt',
  },
  {
    id: 22,
    patient_name: 'Opaline Schriren',
    admission_date: '06/04/2022',
    discharge_date: '04/07/2023',
    gender: 'Female',
    room: "Yellow Nodding Lady's Tresses",
    birth: '30/06/2017',
    hr: 157,
    rr: 26,
    spo2: 68,
    temp: 27.4,
    sistolik: 179,
    diastolik: 75,
    id_card: 1031297809,
    address: '6 Eastlawn Park',
    contact: 2715045334,
    education: 'National Technical University (Kiev Politechnical Institute)',
    occupation: 'Product Management',
    height: 265,
    weight: 122,
    blood: 'Khaki',
    covid: true,
    test_type: true,
    result: true,
    referred: 'Mylan Pharmaceuticals Inc.',
    note: 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    ward: 'KI-G',
    photo: 'A.tiff',
  },
  {
    id: 23,
    patient_name: 'Ivan',
    admission_date: '29/09/2022',
    discharge_date: '24/05/2023',
    gender: 'Male',
    room: 'Coastal Plain Yellowtops',
    birth: '13/01/2021',
    hr: 168,
    rr: 30,
    spo2: 47,
    temp: 34.9,
    sistolik: 109,
    diastolik: 49,
    id_card: 9278741894,
    address: '80 Armistice Alley',
    contact: 2357514771,
    education: 'Gardner Webb University',
    occupation: 'Sales',
    height: 160,
    weight: 61,
    blood: 'Fuscia',
    covid: false,
    test_type: true,
    result: true,
    referred: 'Sun Products Corporation',
    note: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    ward: 'PG-CPK',
    photo: 'InHac.avi',
  },
  {
    id: 24,
    patient_name: 'Peter Dunaway',
    admission_date: '18/01/2022',
    discharge_date: '',
    gender: 'Male',
    room: 'Tuckermannopsis Lichen',
    birth: '15/03/2021',
    hr: 94,
    rr: 12,
    spo2: 60,
    temp: 35.6,
    sistolik: 156,
    diastolik: 80,
    id_card: 4418998562,
    address: '8368 Rusk Way',
    contact: 7384052809,
    education: 'Divine Word College',
    occupation: 'Business Development',
    height: 267,
    weight: 67,
    blood: 'Orange',
    covid: true,
    test_type: true,
    result: false,
    referred: 'McNeil Consumer Healthcare Div McNeil-PPC, Inc',
    note: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    ward: 'PG-WPD',
    photo: 'OrciLuctus.mp3',
  },
  {
    id: 25,
    patient_name: 'Zora Pringle',
    admission_date: '22/06/2022',
    discharge_date: '16/07/2023',
    gender: 'Female',
    room: 'Rock Rosemary',
    birth: '29/04/2019',
    hr: 109,
    rr: 13,
    spo2: 47,
    temp: 28.2,
    sistolik: 161,
    diastolik: 35,
    id_card: 3040040812,
    address: '2690 Bultman Trail',
    contact: 9443493067,
    education: 'Marquette University',
    occupation: 'Research and Development',
    height: 58,
    weight: 22,
    blood: 'Puce',
    covid: true,
    test_type: false,
    result: true,
    referred: 'K.N.Life Co., Ltd.',
    note: 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    ward: 'AU-NT',
    photo: 'InterdumEuTincidunt.xls',
  },
  {
    id: 26,
    patient_name: 'Dylan Rosling',
    admission_date: '29/05/2022',
    discharge_date: '30/06/2023',
    gender: 'Male',
    room: 'American Nailwort',
    birth: '25/06/2018',
    hr: 80,
    rr: 26,
    spo2: 64,
    temp: 25.6,
    sistolik: 152,
    diastolik: 30,
    id_card: 6544580052,
    address: '17 Corry Court',
    contact: 3387049877,
    education: 'Wilbur Wright College',
    occupation: 'Services',
    height: 203,
    weight: 136,
    blood: 'Yellow',
    covid: true,
    test_type: true,
    result: true,
    referred: 'Heel Inc',
    note: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    ward: 'CA-AB',
    photo: 'Gravida.doc',
  },
  {
    id: 27,
    patient_name: 'Alaric',
    admission_date: '28/03/2022',
    discharge_date: '26/05/2023',
    gender: 'Male',
    room: 'Diamondleaf Fogfruit',
    birth: '15/09/2020',
    hr: 100,
    rr: 27,
    spo2: 82,
    temp: 35.6,
    sistolik: 159,
    diastolik: 67,
    id_card: 4043650122,
    address: '18 Ryan Avenue',
    contact: 6980026734,
    education: 'Universitas Haluoleo',
    occupation: 'Marketing',
    height: 293,
    weight: 171,
    blood: 'Red',
    covid: false,
    test_type: false,
    result: false,
    referred: 'Church & Dwight Canada Corp.',
    note: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    ward: 'ID-PA',
    photo: 'AdipiscingMolestieHendrerit.avi',
  },
  {
    id: 28,
    patient_name: 'Amalie Hanhard',
    admission_date: '01/03/2022',
    discharge_date: '',
    gender: 'Female',
    room: 'Exasperated Melanelia Lichen',
    birth: '17/08/2019',
    hr: 169,
    rr: 12,
    spo2: 45,
    temp: 29.1,
    sistolik: 112,
    diastolik: 88,
    id_card: 6672034969,
    address: '04132 Sullivan Hill',
    contact: 6082657277,
    education: 'Bourgas University "Prof. Assen Zlatarov"',
    occupation: 'Business Development',
    height: 141,
    weight: 119,
    blood: 'Puce',
    covid: false,
    test_type: true,
    result: false,
    referred: 'Allergy Laboratories, Inc.',
    note: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    ward: 'BR-RO',
    photo: 'QuisOdioConsequat.mp3',
  },
  {
    id: 29,
    patient_name: 'Alaric Rasendriya Aniko',
    admission_date: '03/09/2022',
    discharge_date: '07/06/2023',
    gender: 'Male',
    room: 'Jamaican Filmy Fern',
    birth: '21/11/2018',
    hr: 81,
    rr: 26,
    spo2: 77,
    temp: 29.6,
    sistolik: 188,
    diastolik: 55,
    id_card: 3948089817,
    address: '359 Starling Court',
    contact: 9606231557,
    education: 'Plekhanov Russian Academy of Economics',
    occupation: 'Support',
    height: 73,
    weight: 96,
    blood: 'Violet',
    covid: true,
    test_type: false,
    result: true,
    referred: 'NorthStar Rx LLC',
    note: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    ward: 'CA-BC',
    photo: 'EstRisusAuctor.mpeg',
  },
  {
    id: 30,
    patient_name: 'Cherry Laborde',
    admission_date: '10/08/2022',
    discharge_date: '15/07/2023',
    gender: 'Female',
    room: 'Forskohlii',
    birth: '09/11/2017',
    hr: 58,
    rr: 27,
    spo2: 38,
    temp: 35.4,
    sistolik: 153,
    diastolik: 92,
    id_card: 4509086693,
    address: '0 Nelson Road',
    contact: 9165573628,
    education: 'Hunan University',
    occupation: 'Services',
    height: 273,
    weight: 46,
    blood: 'Aquamarine',
    covid: true,
    test_type: true,
    result: false,
    referred: 'Medline Industries, Inc.',
    note: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    ward: 'GH-WP',
    photo: 'Ac.ppt',
  },
];

export default patient_dummy_data
